name: Build and Publish mdllama DEB and RPM

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref'
        required: false
      release_tag:
        description: 'Release tag'
        required: false


permissions:
  contents: write

jobs:
  build-deb:
    runs-on: Debian
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Clean up old packages before build
        run: |
          rm -rf repo/

      - name: Run build-mdllama-deb.sh
        run: |
          chmod +x ./build-mdllama-deb.sh
          ./build-mdllama-deb.sh

      - name: Upload debian repo artifact
        uses: actions/upload-artifact@v4
        id: upload-deb
        with:
          name: debian-repo
          path: repo/**

  build-rpm:
    runs-on: Fedora
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Clean up old packages before build
        run: |
          rm -rf rpm-out/

      - name: Run build-mdllama-rpm.sh
        run: |
          chmod +x ./build-mdllama-rpm.sh
          ./build-mdllama-rpm.sh

      - name: Upload fedora rpm artifact
        uses: actions/upload-artifact@v4
        id: upload-rpm
        with:
          name: fedora-rpm
          path: rpm-out/**

  deploy:
    runs-on: ubuntu-latest
    needs: [build-deb, build-rpm]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4


      - name: Download debian repo artifact (stable)
        uses: actions/download-artifact@v4
        with:
          name: debian-repo
          path: debian/

      - name: Download fedora rpm artifact (stable)
        uses: actions/download-artifact@v4
        with:
          name: fedora-rpm
          path: fedora/

      - name: Merge with existing gh-pages content
        run: |
          # Clone existing gh-pages branch
          git clone --branch gh-pages --single-branch https://github.com/QinCai-rui/packages.git existing-gh-pages || echo "No existing gh-pages branch"
          
          # Use rsync to merge existing content with new content
          if [ -d "existing-gh-pages" ]; then
            rsync -av existing-gh-pages/ ./ --exclude='.git'
          fi
          
          # Remove the cloned directory so it doesn't get deployed
          rm -rf existing-gh-pages


      - name: List all published packages
        run: |
          echo "DEB packages:" && find debian/ -name '*.deb' 2>/dev/null || echo "No debian packages"
          echo "DEB testing packages:" && find debian-testing/ -name '*.deb' 2>/dev/null || echo "No debian-testing packages"
          echo "RPM packages:" && find fedora/ -name '*.rpm' 2>/dev/null || echo "No fedora packages"
          echo "RPM testing packages:" && find fedora-testing/ -name '*.rpm' 2>/dev/null || echo "No fedora-testing packages"

      - name: Clean up extra files before deploy
        run: |
          rm -f LICENSE
          find . -maxdepth 2 -name '*.sh' -exec rm -f {} +

      - name: Deploy to gh-pages (debian/, debian-testing/, fedora/, fedora-testing/)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          cname: packages.qincai.xyz
