name: Build and Publish mdllama DEB and RPM 

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref'
        required: false
      release_tag:
        description: 'Release tag'
        required: false

permissions:
  contents: write

jobs:
  clean-stable-repos:
    runs-on: ubuntu-latest
    outputs:
      working-branch: ${{ steps.create-branch.outputs.working-branch }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Create and push 'working' branch with merged content
        id: create-branch
        run: |
          # Configure git author so commit is attributed
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create a unique working branch name to avoid conflicts
          WORKING_BRANCH="working-stable-$(date +%s)-${{ github.run_id }}"
          
          # Create working branch from main (preserving build scripts)
          git checkout -b "$WORKING_BRANCH"
          
          # Fetch and merge gh-pages content, removing target directories
          if git ls-remote --exit-code --heads origin gh-pages; then
            echo "gh-pages branch exists, fetching content..."
            git fetch origin gh-pages
            
            # Create temp directory and extract gh-pages files
            mkdir -p temp-gh-pages
            git --work-tree=temp-gh-pages checkout origin/gh-pages -- . 2>/dev/null || echo "No files in gh-pages"
            
            # Remove target directories
            rm -rf temp-gh-pages/debian temp-gh-pages/fedora
            
            # Copy remaining gh-pages content to working branch
            if [ -d "temp-gh-pages" ]; then
              cp -r temp-gh-pages/* . 2>/dev/null || echo "No files to copy"
              rm -rf temp-gh-pages
            fi
          else
            echo "No gh-pages branch found, starting fresh"
          fi
          
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: merge main branch with cleaned gh-pages content"
            git push --set-upstream origin "$WORKING_BRANCH"
          fi
          
          # Set the output for other jobs to use
          echo "working-branch=$WORKING_BRANCH" >> $GITHUB_OUTPUT

  build-deb:
    needs: clean-stable-repos
    runs-on: Debian
    timeout-minutes: 10  # Fails if job doesn't start/finish in 10 minutes
    steps:
      - name: Checkout working branch
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.clean-stable-repos.outputs.working-branch }}

      - name: Clean up old packages before build
        run: |
          rm -rf repo/

      - name: Run build-mdllama-deb.sh
        run: |
          chmod +x ./build-mdllama-deb.sh
          ./build-mdllama-deb.sh

      - name: Upload debian repo artifact
        uses: actions/upload-artifact@v4
        id: upload-deb
        with:
          name: debian-repo
          path: repo/**

  build-rpm:
    needs: clean-stable-repos
    runs-on: Fedora
    timeout-minutes: 10  # Fails if job doesn't start/finish in 10 minutes
    steps:
      - name: Checkout working branch
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.clean-stable-repos.outputs.working-branch }}

      - name: Clean up old packages before build
        run: |
          rm -rf rpm-out/

      - name: Run build-mdllama-rpm.sh
        run: |
          chmod +x ./build-mdllama-rpm.sh
          ./build-mdllama-rpm.sh

      - name: Upload fedora rpm artifact
        uses: actions/upload-artifact@v4
        with:
          name: fedora-rpm
          path: rpm-out/**

  deploy:
    runs-on: ubuntu-latest
    needs: [build-deb, build-rpm]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4


      - name: Download debian repo artifact (stable)
        uses: actions/download-artifact@v4
        with:
          name: debian-repo
          path: debian/

      - name: Download fedora rpm artifact (stable)
        uses: actions/download-artifact@v4
        with:
          name: fedora-rpm
          path: fedora/

      - name: Merge with existing gh-pages content
        run: |
          # Clone existing gh-pages branch
          git clone --branch gh-pages --single-branch https://${{ secrets.GITHUB_TOKEN }}@github.com/QinCai-rui/packages.git existing-gh-pages || echo "No existing gh-pages branch"
          
          # Clone working branch to get the cleaned state
          WORKING_BRANCH="${{ needs.clean-stable-repos.outputs.working-branch }}"
          if [ -n "$WORKING_BRANCH" ]; then
            git clone --branch "$WORKING_BRANCH" --single-branch https://${{ secrets.GITHUB_TOKEN }}@github.com/QinCai-rui/packages.git working-branch || echo "No working branch found"
          fi
          
          # Start with working branch content (which has removals applied)
          if [ -d "working-branch" ]; then
            rsync -av working-branch/ ./ --exclude='.git'
          fi
          
          # Merge back any other directories from gh-pages that weren't removed
          if [ -d "existing-gh-pages" ]; then
            # Copy back non-target directories from gh-pages
            for dir in existing-gh-pages/*/; do
              dirname=$(basename "$dir")
              if [ "$dirname" != "debian" ] && [ "$dirname" != "fedora" ]; then
                rsync -av "$dir" "./"
              fi
            done
          fi
          
          # Remove the cloned directories so they don't get deployed
          rm -rf existing-gh-pages working-branch


      - name: List all published packages
        run: |
          echo "DEB packages:" && find debian/ -name '*.deb' 2>/dev/null || echo "No debian packages"
          echo "DEB testing packages:" && find debian-testing/ -name '*.deb' 2>/dev/null || echo "No debian-testing packages"
          echo "RPM packages:" && find fedora/ -name '*.rpm' 2>/dev/null || echo "No fedora packages"
          echo "RPM testing packages:" && find fedora-testing/ -name '*.rpm' 2>/dev/null || echo "No fedora-testing packages"

      - name: Clean up extra files before deploy
        run: |
          rm -f LICENSE
          find . -maxdepth 2 -name '*.sh' -exec rm -f {} +

      - name: Deploy to gh-pages (debian/, debian-testing/, fedora/, fedora-testing/)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          cname: packages.qincai.xyz

      - name: Clean up temporary working branch
        if: always()
        run: |
          WORKING_BRANCH="${{ needs.clean-stable-repos.outputs.working-branch }}"
          if [ -n "$WORKING_BRANCH" ]; then
            git push origin --delete "$WORKING_BRANCH" || echo "Working branch already cleaned up or doesn't exist"
          fi
