name: Build and Publish mdllama DEB and RPM to GitHub Pages PPA

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref'
        required: false
      release_tag:
        description: 'Release tag'
        required: false

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: Debian
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Run build-mdllama-deb.sh
        run: |
          chmod +x ./build-mdllama-deb.sh
          ./build-mdllama-deb.sh

      - name: Deploy to gh-pages (debian/)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: gh-pages
          destination_dir: debian
          cname: packages.qincai.xyz

  build-rpm:
    runs-on: Fedora
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Run build-mdllama-rpm.sh
        run: |
          chmod +x ./build-mdllama-rpm.sh
          ./build-mdllama-rpm.sh

      - name: Deploy to gh-pages (fedora/)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          destination_dir: fedora
          cname: packages.qincai.xyz
