name: Build and Publish mdllama DEB and RPM

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref'
        required: false
      release_tag:
        description: 'Release tag'
        required: false

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: Debian
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Clone gh-pages branch for old packages
        run: |
          git clone --branch gh-pages --single-branch https://github.com/QinCai-rui/packages.git oldrepo

      - name: Run build-mdllama-deb.sh
        run: |
          chmod +x ./build-mdllama-deb.sh
          ./build-mdllama-deb.sh

      - name: Upload debian repo artifact
        uses: actions/upload-artifact@v4
        id: upload-deb
        with:
          name: debian-repo
          path: repo/**

  build-rpm:
    runs-on: Fedora
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Clone gh-pages branch for old packages
        run: |
          git clone --branch gh-pages --single-branch https://github.com/QinCai-rui/packages.git oldrepo

      - name: Run build-mdllama-rpm.sh
        run: |
          chmod +x ./build-mdllama-rpm.sh
          ./build-mdllama-rpm.sh

      - name: Upload fedora rpm artifact
        uses: actions/upload-artifact@v4
        id: upload-rpm
        with:
          name: fedora-rpm
          path: rpm-out/**

  deploy:
    runs-on: ubuntu-latest
    needs: [build-deb, build-rpm]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Download debian repo artifact
        uses: actions/download-artifact@v4
        with:
          name: debian-repo
          path: debian/

      - name: Download fedora rpm artifact
        uses: actions/download-artifact@v4
        with:
          name: fedora-rpm
          path: fedora/

      - name: List all published packages
        run: |
          echo "DEB packages:" && find debian/ -name '*.deb'
          echo "RPM packages:" && find fedora/ -name '*.rpm'

      - name: Clean up extra files before deploy
        run: |
          rm -f LICENSE
          find . -maxdepth 2 -name '*.sh' -exec rm -f {} +

      - name: Deploy to gh-pages (debian/ and fedora/)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          cname: packages.qincai.xyz
