name: Build and Publish mdllama DEB and RPM (testing branch)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (optional)'
        required: false
      release_tag:
        description: 'Release tag (optional)'
        required: false

permissions:
  contents: write

jobs:
  clean-testing-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: true

      - name: Remove debian-testing and fedora-testing
        run: |
          rm -rf debian-testing fedora-testing

      - name: Commit and push removals
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: clean debian-testing and fedora-testing before build"

  build-deb-testing:
    needs: clean-testing-repos
    runs-on: Debian
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Clean up old packages before build
        run: |
          rm -rf repo/

      - name: Run build-mdllama-deb-testing.sh
        run: |
          chmod +x ./build-mdllama-deb-testing.sh
          ./build-mdllama-deb-testing.sh

      - name: Upload debian repo artifact (testing)
        uses: actions/upload-artifact@v4
        id: upload-deb-testing
        with:
          name: debian-repo-testing
          path: repo/**

  build-rpm-testing:
    needs: clean-testing-repos
    runs-on: Fedora
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Clean up old packages before build
        run: |
          rm -rf rpm-out/

      - name: Run build-mdllama-rpm-testing.sh
        run: |
          chmod +x ./build-mdllama-rpm-testing.sh
          ./build-mdllama-rpm-testing.sh

      - name: Upload fedora rpm artifact (testing)
        uses: actions/upload-artifact@v4
        id: upload-rpm-testing
        with:
          name: fedora-rpm-testing
          path: rpm-out/**

  deploy-testing:
    runs-on: ubuntu-latest
    needs: [build-deb-testing, build-rpm-testing]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Download debian repo artifact (testing)
        uses: actions/download-artifact@v4
        with:
          name: debian-repo-testing
          path: repo/

      - name: Download fedora rpm artifact (testing)
        uses: actions/download-artifact@v4
        with:
          name: fedora-rpm-testing
          path: rpm-out/

      - name: Reorganize artifacts to proper locations
        run: |
          # Move debian repo to correct location
          if [ -d "repo" ]; then
            mv repo debian-testing
          fi
          
          # Move fedora rpm to correct location  
          if [ -d "rpm-out" ]; then
            mv rpm-out fedora-testing
          fi

      - name: Merge with existing gh-pages content
        run: |
          # Clone existing gh-pages branch
          git clone --branch gh-pages --single-branch https://${{ secrets.GITHUB_TOKEN }}@github.com/QinCai-rui/packages.git existing-gh-pages || echo "No existing gh-pages branch"
          
          # Use rsync to merge existing content with new content
          if [ -d "existing-gh-pages" ]; then
            rsync -av existing-gh-pages/ ./ --exclude='.git'
          fi
          
          # Remove the cloned directory so it doesn't get deployed
          rm -rf existing-gh-pages

      - name: List all published packages (testing)
        run: |
          echo "DEB packages:" && find debian/ -name '*.deb' 2>/dev/null || echo "No debian packages"
          echo "DEB testing packages:" && find debian-testing/ -name '*.deb' 2>/dev/null || echo "No debian-testing packages"
          echo "RPM packages:" && find fedora/ -name '*.rpm' 2>/dev/null || echo "No fedora packages"
          echo "RPM testing packages:" && find fedora-testing/ -name '*.rpm' 2>/dev/null || echo "No fedora-testing packages"

      - name: Clean up extra files before deploy (testing)
        run: |
          rm -f LICENSE
          find . -maxdepth 2 -name '*.sh' -exec rm -f {} +

      - name: Deploy to gh-pages (debian/, debian-testing/, fedora/, fedora-testing/)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          cname: packages.qincai.xyz
